/* ZCode packages/ui/src/workspace-file-tree/constants.ts 逐值拷贝（2026-10-01）。
 * 行高 28 + gap 0 = 虚拟行高 28；watch 相关常量随 watcher 一起未接（无 fs watch
 * IPC），保留在案以备上游同步。 */
const WORKSPACE_FILE_TREE_ROW_HEIGHT_PX = 28;
const WORKSPACE_FILE_TREE_ROW_GAP_PX = 0;
export const WORKSPACE_FILE_TREE_VIRTUAL_ROW_HEIGHT_PX =
  WORKSPACE_FILE_TREE_ROW_HEIGHT_PX + WORKSPACE_FILE_TREE_ROW_GAP_PX;

export const WORKSPACE_FILE_TREE_WATCH_DEBOUNCE_MS = 300;
export const WORKSPACE_FILE_TREE_WATCH_REFRESH_CONCURRENCY = 2;
export const WORKSPACE_FILE_TREE_WATCH_BULK_REFRESH_THRESHOLD = 50;
export const WORKSPACE_FILE_TREE_REFRESH_DIRECTORY_TIMEOUT_MS = 15_000;
export const WORKSPACE_FILE_TREE_REFRESH_GIT_TIMEOUT_MS = 8_000;
